name: On Push Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  mvn:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [8, 11, 14, 17, 20]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}

    - name: Build javasizer
      run: mvn package